version: "3"
services:
  dnsmasq:
    container_name: dnsmasq
    cap_add:
      - NET_ADMIN
    image: hoshinorei/dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    restart: always
    networks:
      qbittorrent-net:
        ipv4_address: 10.10.10.250


networks:
  qbittorrent-net:
    external: true
    name: macnet