version: "3.7"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8099
    volumes:
      - .data/config:/config
      - ./downloads:/downloads
    restart: unless-stopped
    networks:
      qbittorrent-net:
        ipv4_address: 10.10.10.204

networks:
  qbittorrent-net:
    external: true
    name: macnet