version: "3.7"
services:
  aria2:
    image: p3terx/aria2-pro:latest
    container_name: aria2
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=kycer.site
      - RPC_PORT=6800
      - LISTEN_PORT=6888
    volumes:
      - ./data/config:/config
      - ./downloads:/downloads
    restart: unless-stopped
    networks:
      aria2-net:
        ipv4_address: 10.10.10.205

networks:
  aria2-net:
    external: true
    name: macnet