version: '2.0'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./servers:/etc/nginx/servers
      - ./log:/var/log/nginx
      - ./www:/usr/share/nginx/html
      - ./cert:/etc/nginx/cert
    networks:
      nginx-net:
        ipv4_address: 10.10.10.200
networks:
  nginx-net:
    external: true
    name: macnet